### ISSUE TITLE
Crowded "theories" folder

### ISSUE THREAD

**Issue by vbdr** [jorge-ramirez-upm/RepTate#118]
The "theories" folder is quite crowded. Should we think about creating subfolders, e.g. one per application, and group all related files together? @jorge-ramirez-upm

**Comment by jorge-ramirez-upm** [comment]
Yes, I totally agree... We should also keep a clear naming strategy for files, classes and everything else.

**Comment by jorge-ramirez-upm** [comment]
Re-thinking this after a couple of years. It doesn't seem to be problematic to have all theories in the same folder.
