### ISSUE TITLE
Save polyconf does not work on Windows when folders have latin characters

### ISSUE THREAD

**Issue by jorge-ramirez-upm** [jorge-ramirez-upm/RepTate#136]

**Comment by vbdr** [comment]
@jorge-ramirez-upm Could you provide more info? I cannot replicate that issue when I save a polyconf file (from a Tobita Batch theory) to a folder named "**test latín**" (note the **í**)

**Comment by vbdr** [comment]
Fixed in a4c299639f86a2c72ec00772d2ecb3a1afc9c55f
