### ISSUE TITLE
Error when closing a theory

### ISSUE THREAD

**Issue by vbdr** [jorge-ramirez-upm/RepTate#137]
Error when closing a theory tab in GUI RepTate.

------------------------------------------------------------
Error Traceback:
   File "gui/QDataSet.py", line 745, in handle_thTabCloseRequested
    self.do_theory_delete(th_name)  #call DataSet.do_theory_delete
AttributeError: 'QDataSet' object has no attribute 'do_theory_delete'

**Comment by jorge-ramirez-upm** [comment]
Solved. I changed the names of the do_* functions in the CL version to simplify notation.
