### ISSUE TITLE
colorama in RepTateCL

### ISSUE THREAD

**Issue by vbdr** [jorge-ramirez-upm/RepTate#140]
**Describe the bug**
The terminal keeps the last colour used when RepTateCL quits

On MacOs terminal, simply launching RepTate-CL and immediately `quit()` can reproduce this issue.

**Comment by jorge-ramirez-upm** [comment]
This does not seem to happen on Windows... Can you give a list of steps to get this behaviour?

**Comment by vbdr** [comment]
Closing this issue as "it is working normally now"
