### ISSUE TITLE
Error  "TypeError: resizeSection(self, int, int): argument 2 has unexpected type 'float'"

### ISSUE THREAD

**Issue by jorge-jardim** [jorge-ramirez-upm/RepTate#149]
By clicking in any icon of the app I get the following error

**20231031 092806 RepTate ERROR:   File "C:\Users\jorgem63\.conda\envs\RepTate\Lib\site-packages\RepTate\gui\QApplicationManager.py", line 187, in <lambda><br>    self.actionLVE.triggered.connect(lambda: self.handle_new_app('LVE'))<br>                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^<br>  File "C:\Users\jorgem63\.conda\envs\RepTate\Lib\site-packages\RepTate\gui\QApplicationManager.py", line 466, in handle_new_app<br>    self.Qopen_app(app_name,<br>  File "C:\Users\jorgem63\.conda\envs\RepTate\Lib\site-packages\RepTate\gui\QApplicationManager.py", line 456, in Qopen_app<br>    newapp.createNew_Empty_Dataset(<br>  File "C:\Users\jorgem63\.conda\envs\RepTate\Lib\site-packages\RepTate\gui\QApplicationWindow.py", line 1563, in createNew_Empty_Dataset<br>    ds = QDataSet(name=ds_name, parent=self)<br>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>  File "C:\Users\jorgem63\.conda\envs\RepTate\Lib\site-packages\RepTate\gui\QDataSet.py", line 233, in __init__<br>    hd.resizeSection(0, w)<br>TypeError: resizeSection(self, int, int): argument 2 has unexpected type 'float'<br>**

**Comment by jorge-ramirez-upm** [comment]
I think this problem has been solved in new versions
