### ISSUE TITLE
Warning in terminal when using multithreads

### ISSUE THREAD

**Issue by vbdr** [jorge-ramirez-upm/RepTate#59]
Warning:

QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)

is printed in terminal when calculating theory. It seems that calling the "thTextBox" widget in Theory.py is not allowed outside the main Qt loop.
A solution might be to use Qt signals and slots to print messages in thTextBox from a thread.

**Comment by vbdr** [comment]
Qprint is now used via a pyqtSignal.

**Comment by jorge-ramirez-upm** [comment]
That is great!
