### ISSUE TITLE
Me minimisation in Likhtman-McLeish theory

### ISSUE THREAD

**Issue by vbdr** [jorge-ramirez-upm/RepTate#67]
The value of 'Me' is not minimised during the fitting procedure of the Likhtman-McLeish theory

**Comment by vbdr** [comment]
This is Daniel typing!!

I think the problem is that the theory is not doing the interpolation between Z values correctly.  As an experiment, try changing Me by a small amount, and click calculate, then change it a bit more, and click calculate, and keep doing this. What you will find is that the theory sometimes doesn't change, then suddenly it changes by a large amount, then it doesn't change again, etc.  I think probably what is happening is that the minimisation procedure tries a small change in Me, realises that it does not change the curves, then does not bother changing Me again and reports that the error in Me is not known.

The Z interpolation didn't actually work properly in the old Reptate, in fact. So i think this is a legacy bug! But probably the minimisation procedure was different in old Reptate.

**Comment by jorge-ramirez-upm** [comment]
Hi! Not only the minimisation procedure was different, also the interpolation is different! Now it is handled by numpy, so I expect it to be correct. Lately, I noticed that the error is inf in many theories... Maybe we changed the minimisation method?

**Comment by vbdr** [comment]
That's right, I recently removed the default minimisation method that was "trf" in `curve_fit()`. It means that for unbounded problem `curve_fit()` uses "lm" method, or "trf" method for a bounded problem.
Because all parameters in Likthman-McLeish theory are unbounded, the default method was "lm"

Putting back `method=trf` in `curve_fit()` shows errors 'correctly' but it seems that Me is still not minimised.

**Comment by jorge-ramirez-upm** [comment]
Victor, please check if the theory works now on your Mac. I think it should be better. If it does, we can safely close this issue.

**Comment by vbdr** [comment]
It works for me!
