### ISSUE TITLE
Bug in MWD Discr

### ISSUE THREAD

**Issue by jorge-ramirez-upm** [jorge-ramirez-upm/RepTate#68]
AttributeError: 'GUITheoryDiscrMWD' object has no attribute 'bin_edges'

**Comment by vbdr** [comment]
I don't see this error when running `tests/RepTate_Test_MWD.py`. When does it occur?

**Comment by jorge-ramirez-upm** [comment]
Strange... When I run Reptate from the command line, open the same gpc file
as in the test and then open a new MWDiscr theory, the program freezes and
I get that error.
I don't see the error if just run the test.

[image: Industriales]
*ESCUELA SUPERIOR DE INGENIEROS INDUSTRIALES*
UNIVERSIDAD POLITÉCNICA DE MADRID

* Jorge Ramírez García | *DEPARTAMENTO DE INGENIERÍA QUÍMICA INDUSTRIAL Y
MEDIO AMBIENTE
José Gutiérrez Abascal, 2 | 28006 Madrid
*TEL: *+34 91 067 7303 *| FAX: +34 91 336 3009*
*E-MAIL: *jorge.ramirez@upm.es <%20jorge.ramirez@upm.es>
*WEB: **http://blogs.upm.es/compsoftmatter/
<http://blogs.upm.es/compsoftmatter/>*

**Comment by vbdr** [comment]
Problem corrected by using single-thread `calculate()` when a new theory is opened.
