### ISSUE TITLE
Gt app: Save i-Rheo and Schwarzl views to a tts file

### ISSUE THREAD

**Issue by jorge-ramirez-upm** [jorge-ramirez-upm/RepTate#84]

**Comment by jorge-ramirez-upm** [comment]
Added a button next to the view combobox to save the data in the current view. The function is still incomplete.

**Comment by vbdr** [comment]
We can now save all views in a .txt file. I think we can close this issue, unless we want a special treatment for the for iRheo and Schwarzl views to produce a .tts file?

**Comment by jorge-ramirez-upm** [comment]
We can close the issue. The use can easily change the file extension to open the file in the LVE module.
